name: Node.js Package

on:
  push:
    branches: [ Develop ]
  pull_request:
    branches: [ Develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Node LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          
      - name: Build client API
        run: npm run build

      - name: Create NPM package
        run: npm pack

      - name: Upload NPM package
        uses: actions/upload-artifact@v2
        with:
          name: client-api
          path: client-api-*.tgz
