name: Node.js Package

permissions:
  packages: write

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Node LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - run: echo "//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN }}">.npmrc

      - name: Install npm package
        run: npm install

      - name: Build client API
        run: npm run build
        
      - run: |
          ls -al

      - name: Get Variable value
        run: |
          echo "NPM_PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          echo "NPM_PACKAGE_NAME=$(node -p "require('./package.json').name")" >> $GITHUB_ENV

      - name: Create NPM publish
        run: npm publish
