/**
 * GameTrip.API
 * GameTrip API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreateLocationDto } from '../models/CreateLocationDto';
import { HttpFile } from '../http/http';

export class CreateLocationWithGameAndPictureDto {
    'location'?: CreateLocationDto;
    'gamesIds'?: Array<string> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "location",
            "baseName": "location",
            "type": "CreateLocationDto",
            "format": ""
        },
        {
            "name": "gamesIds",
            "baseName": "gamesIds",
            "type": "Array<string>",
            "format": "uuid"
        }    ];

    static getAttributeTypeMap() {
        return CreateLocationWithGameAndPictureDto.attributeTypeMap;
    }

    public constructor() {
    }
}

