/**
 * GameTrip.API
 * GameTrip API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CustomAttributeData } from '../models/CustomAttributeData';
import { FieldAttributes } from '../models/FieldAttributes';
import { MemberTypes } from '../models/MemberTypes';
import { Module } from '../models/Module';
import { RuntimeFieldHandle } from '../models/RuntimeFieldHandle';
import { Type } from '../models/Type';
import { HttpFile } from '../http/http';

export class FieldInfo {
    'name'?: string | null;
    'declaringType'?: Type;
    'reflectedType'?: Type;
    'module'?: Module;
    'customAttributes'?: Array<CustomAttributeData> | null;
    'isCollectible'?: boolean;
    'metadataToken'?: number;
    'memberType'?: MemberTypes;
    'attributes'?: FieldAttributes;
    'fieldType'?: Type;
    'isInitOnly'?: boolean;
    'isLiteral'?: boolean;
    'isNotSerialized'?: boolean;
    'isPinvokeImpl'?: boolean;
    'isSpecialName'?: boolean;
    'isStatic'?: boolean;
    'isAssembly'?: boolean;
    'isFamily'?: boolean;
    'isFamilyAndAssembly'?: boolean;
    'isFamilyOrAssembly'?: boolean;
    'isPrivate'?: boolean;
    'isPublic'?: boolean;
    'isSecurityCritical'?: boolean;
    'isSecuritySafeCritical'?: boolean;
    'isSecurityTransparent'?: boolean;
    'fieldHandle'?: RuntimeFieldHandle;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "declaringType",
            "baseName": "declaringType",
            "type": "Type",
            "format": ""
        },
        {
            "name": "reflectedType",
            "baseName": "reflectedType",
            "type": "Type",
            "format": ""
        },
        {
            "name": "module",
            "baseName": "module",
            "type": "Module",
            "format": ""
        },
        {
            "name": "customAttributes",
            "baseName": "customAttributes",
            "type": "Array<CustomAttributeData>",
            "format": ""
        },
        {
            "name": "isCollectible",
            "baseName": "isCollectible",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "metadataToken",
            "baseName": "metadataToken",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "memberType",
            "baseName": "memberType",
            "type": "MemberTypes",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "FieldAttributes",
            "format": ""
        },
        {
            "name": "fieldType",
            "baseName": "fieldType",
            "type": "Type",
            "format": ""
        },
        {
            "name": "isInitOnly",
            "baseName": "isInitOnly",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isLiteral",
            "baseName": "isLiteral",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isNotSerialized",
            "baseName": "isNotSerialized",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isPinvokeImpl",
            "baseName": "isPinvokeImpl",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isSpecialName",
            "baseName": "isSpecialName",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isStatic",
            "baseName": "isStatic",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isAssembly",
            "baseName": "isAssembly",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isFamily",
            "baseName": "isFamily",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isFamilyAndAssembly",
            "baseName": "isFamilyAndAssembly",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isFamilyOrAssembly",
            "baseName": "isFamilyOrAssembly",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isPrivate",
            "baseName": "isPrivate",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isPublic",
            "baseName": "isPublic",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isSecurityCritical",
            "baseName": "isSecurityCritical",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isSecuritySafeCritical",
            "baseName": "isSecuritySafeCritical",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isSecurityTransparent",
            "baseName": "isSecurityTransparent",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "fieldHandle",
            "baseName": "fieldHandle",
            "type": "RuntimeFieldHandle",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FieldInfo.attributeTypeMap;
    }

    public constructor() {
    }
}



