/**
 * GameTrip.API
 * GameTrip API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LikedGame } from '../models/LikedGame';
import { LocationDto } from '../models/LocationDto';
import { Picture } from '../models/Picture';
import { HttpFile } from '../http/http';

export class GameDto {
    'name'?: string | null;
    'description'?: string | null;
    'editor'?: string | null;
    'releaseDate'?: number | null;
    'locations'?: Array<LocationDto> | null;
    'pictures'?: Array<Picture> | null;
    'likedGames'?: Array<LikedGame> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "editor",
            "baseName": "editor",
            "type": "string",
            "format": ""
        },
        {
            "name": "releaseDate",
            "baseName": "releaseDate",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "locations",
            "baseName": "locations",
            "type": "Array<LocationDto>",
            "format": ""
        },
        {
            "name": "pictures",
            "baseName": "pictures",
            "type": "Array<Picture>",
            "format": ""
        },
        {
            "name": "likedGames",
            "baseName": "likedGames",
            "type": "Array<LikedGame>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GameDto.attributeTypeMap;
    }

    public constructor() {
    }
}

