/**
 * GameTrip.API
 * GameTrip API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListCommentDto } from '../models/ListCommentDto';
import { ListLikedGameDto } from '../models/ListLikedGameDto';
import { ListLikedLocationDto } from '../models/ListLikedLocationDto';
import { HttpFile } from '../http/http';

export class GameTripUserDto {
    'userId'?: string | null;
    'userName'?: string | null;
    'email'?: string | null;
    'comments'?: Array<ListCommentDto> | null;
    'likedGames'?: Array<ListLikedGameDto> | null;
    'likedLocations'?: Array<ListLikedLocationDto> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "userName",
            "baseName": "userName",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "comments",
            "baseName": "comments",
            "type": "Array<ListCommentDto>",
            "format": ""
        },
        {
            "name": "likedGames",
            "baseName": "likedGames",
            "type": "Array<ListLikedGameDto>",
            "format": ""
        },
        {
            "name": "likedLocations",
            "baseName": "likedLocations",
            "type": "Array<ListLikedLocationDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GameTripUserDto.attributeTypeMap;
    }

    public constructor() {
    }
}

