/**
 * GameTrip.API
 * GameTrip API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListCommentDto } from '../models/ListCommentDto';
import { ListGameDto } from '../models/ListGameDto';
import { ListLikedLocationDto } from '../models/ListLikedLocationDto';
import { ListPictureDto } from '../models/ListPictureDto';
import { HttpFile } from '../http/http';

export class GetLocationDto {
    'id'?: string | null;
    'name'?: string | null;
    'description'?: string | null;
    'latitude'?: number;
    'longitude'?: number;
    'pictures'?: Array<ListPictureDto> | null;
    'games'?: Array<ListGameDto> | null;
    'comments'?: Array<ListCommentDto> | null;
    'likedLocations'?: Array<ListLikedLocationDto> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "latitude",
            "baseName": "latitude",
            "type": "number",
            "format": "double"
        },
        {
            "name": "longitude",
            "baseName": "longitude",
            "type": "number",
            "format": "double"
        },
        {
            "name": "pictures",
            "baseName": "pictures",
            "type": "Array<ListPictureDto>",
            "format": ""
        },
        {
            "name": "games",
            "baseName": "games",
            "type": "Array<ListGameDto>",
            "format": ""
        },
        {
            "name": "comments",
            "baseName": "comments",
            "type": "Array<ListCommentDto>",
            "format": ""
        },
        {
            "name": "likedLocations",
            "baseName": "likedLocations",
            "type": "Array<ListLikedLocationDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetLocationDto.attributeTypeMap;
    }

    public constructor() {
    }
}

