/**
 * GameTrip.API
 * GameTrip API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GameTripUser } from '../models/GameTripUser';
import { Location } from '../models/Location';
import { HttpFile } from '../http/http';

export class LikedLocation {
    'idLikedLocation'?: string;
    'locationId'?: string;
    'location'?: Location;
    'userId'?: string;
    'user'?: GameTripUser;
    'vote'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "idLikedLocation",
            "baseName": "idLikedLocation",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "locationId",
            "baseName": "locationId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "Location",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "GameTripUser",
            "format": ""
        },
        {
            "name": "vote",
            "baseName": "vote",
            "type": "number",
            "format": "double"
        }    ];

    static getAttributeTypeMap() {
        return LikedLocation.attributeTypeMap;
    }

    public constructor() {
    }
}

