/**
 * GameTrip.API
 * GameTrip API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LocationNameDto } from '../models/LocationNameDto';
import { HttpFile } from '../http/http';

export class LikedLocationDto {
    'likedLocationId'?: string | null;
    'locationId'?: string | null;
    'location'?: LocationNameDto;
    'usersIds'?: Array<string> | null;
    'nbVote'?: number | null;
    'maxValue'?: number | null;
    'minValue'?: number | null;
    'averageValue'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "likedLocationId",
            "baseName": "likedLocationId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "locationId",
            "baseName": "locationId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "LocationNameDto",
            "format": ""
        },
        {
            "name": "usersIds",
            "baseName": "usersIds",
            "type": "Array<string>",
            "format": "uuid"
        },
        {
            "name": "nbVote",
            "baseName": "nbVote",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "maxValue",
            "baseName": "maxValue",
            "type": "number",
            "format": "double"
        },
        {
            "name": "minValue",
            "baseName": "minValue",
            "type": "number",
            "format": "double"
        },
        {
            "name": "averageValue",
            "baseName": "averageValue",
            "type": "number",
            "format": "double"
        }    ];

    static getAttributeTypeMap() {
        return LikedLocationDto.attributeTypeMap;
    }

    public constructor() {
    }
}

