/**
 * GameTrip.API
 * GameTrip API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GameNameDto } from '../models/GameNameDto';
import { HttpFile } from '../http/http';

export class ListLikedGameDto {
    'likedGameId'?: string | null;
    'gameId'?: string | null;
    'game'?: GameNameDto;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "likedGameId",
            "baseName": "likedGameId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "gameId",
            "baseName": "gameId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "game",
            "baseName": "game",
            "type": "GameNameDto",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListLikedGameDto.attributeTypeMap;
    }

    public constructor() {
    }
}

