/**
 * GameTrip.API
 * GameTrip API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetLocationDto } from '../models/GetLocationDto';
import { LocationUpdateRequestNameDto } from '../models/LocationUpdateRequestNameDto';
import { HttpFile } from '../http/http';

export class ListLocationUpdateRequest {
    'locationId'?: string;
    'location'?: GetLocationDto;
    'requestUpdate'?: Array<LocationUpdateRequestNameDto> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "locationId",
            "baseName": "locationId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "GetLocationDto",
            "format": ""
        },
        {
            "name": "requestUpdate",
            "baseName": "requestUpdate",
            "type": "Array<LocationUpdateRequestNameDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListLocationUpdateRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

