/**
 * GameTrip.API
 * GameTrip API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GameNameDto } from '../models/GameNameDto';
import { PictureDto } from '../models/PictureDto';
import { HttpFile } from '../http/http';

export class LocationUpdateRequestNameDto {
    'idRequestUpdateLocation'?: string;
    'newName'?: string | null;
    'newDescription'?: string | null;
    'newLatitude'?: number | null;
    'newLongitude'?: number | null;
    'pictureId'?: string | null;
    'picture'?: PictureDto;
    'isAddedPicture'?: boolean | null;
    'gameId'?: string | null;
    'game'?: GameNameDto;
    'isAddedGame'?: boolean | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "idRequestUpdateLocation",
            "baseName": "idRequestUpdateLocation",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "newName",
            "baseName": "newName",
            "type": "string",
            "format": ""
        },
        {
            "name": "newDescription",
            "baseName": "newDescription",
            "type": "string",
            "format": ""
        },
        {
            "name": "newLatitude",
            "baseName": "newLatitude",
            "type": "number",
            "format": "double"
        },
        {
            "name": "newLongitude",
            "baseName": "newLongitude",
            "type": "number",
            "format": "double"
        },
        {
            "name": "pictureId",
            "baseName": "pictureId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "picture",
            "baseName": "picture",
            "type": "PictureDto",
            "format": ""
        },
        {
            "name": "isAddedPicture",
            "baseName": "isAddedPicture",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "gameId",
            "baseName": "gameId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "game",
            "baseName": "game",
            "type": "GameNameDto",
            "format": ""
        },
        {
            "name": "isAddedGame",
            "baseName": "isAddedGame",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LocationUpdateRequestNameDto.attributeTypeMap;
    }

    public constructor() {
    }
}

