/**
 * GameTrip.API
 * GameTrip API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CustomAttributeData } from '../models/CustomAttributeData';
import { MemberTypes } from '../models/MemberTypes';
import { Module } from '../models/Module';
import { Type } from '../models/Type';
import { HttpFile } from '../http/http';

export class MemberInfo {
    'memberType'?: MemberTypes;
    'name'?: string | null;
    'declaringType'?: Type;
    'reflectedType'?: Type;
    'module'?: Module;
    'customAttributes'?: Array<CustomAttributeData> | null;
    'isCollectible'?: boolean;
    'metadataToken'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "memberType",
            "baseName": "memberType",
            "type": "MemberTypes",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "declaringType",
            "baseName": "declaringType",
            "type": "Type",
            "format": ""
        },
        {
            "name": "reflectedType",
            "baseName": "reflectedType",
            "type": "Type",
            "format": ""
        },
        {
            "name": "module",
            "baseName": "module",
            "type": "Module",
            "format": ""
        },
        {
            "name": "customAttributes",
            "baseName": "customAttributes",
            "type": "Array<CustomAttributeData>",
            "format": ""
        },
        {
            "name": "isCollectible",
            "baseName": "isCollectible",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "metadataToken",
            "baseName": "metadataToken",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return MemberInfo.attributeTypeMap;
    }

    public constructor() {
    }
}



