/**
 * GameTrip.API
 * GameTrip API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ModelError } from '../models/ModelError';
import { ModelValidationState } from '../models/ModelValidationState';
import { HttpFile } from '../http/http';

export class ModelStateEntry {
    'rawValue'?: any | null;
    'attemptedValue'?: string | null;
    'errors'?: Array<ModelError> | null;
    'validationState'?: ModelValidationState;
    'isContainerNode'?: boolean;
    'children'?: Array<ModelStateEntry> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "rawValue",
            "baseName": "rawValue",
            "type": "any",
            "format": ""
        },
        {
            "name": "attemptedValue",
            "baseName": "attemptedValue",
            "type": "string",
            "format": ""
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<ModelError>",
            "format": ""
        },
        {
            "name": "validationState",
            "baseName": "validationState",
            "type": "ModelValidationState",
            "format": ""
        },
        {
            "name": "isContainerNode",
            "baseName": "isContainerNode",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "children",
            "baseName": "children",
            "type": "Array<ModelStateEntry>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ModelStateEntry.attributeTypeMap;
    }

    public constructor() {
    }
}



