/**
 * GameTrip.API
 * GameTrip API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CustomAttributeData } from '../models/CustomAttributeData';
import { MemberTypes } from '../models/MemberTypes';
import { MethodInfo } from '../models/MethodInfo';
import { Module } from '../models/Module';
import { PropertyAttributes } from '../models/PropertyAttributes';
import { Type } from '../models/Type';
import { HttpFile } from '../http/http';

export class PropertyInfo {
    'name'?: string | null;
    'declaringType'?: Type;
    'reflectedType'?: Type;
    'module'?: Module;
    'customAttributes'?: Array<CustomAttributeData> | null;
    'isCollectible'?: boolean;
    'metadataToken'?: number;
    'memberType'?: MemberTypes;
    'propertyType'?: Type;
    'attributes'?: PropertyAttributes;
    'isSpecialName'?: boolean;
    'canRead'?: boolean;
    'canWrite'?: boolean;
    'getMethod'?: MethodInfo;
    'setMethod'?: MethodInfo;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "declaringType",
            "baseName": "declaringType",
            "type": "Type",
            "format": ""
        },
        {
            "name": "reflectedType",
            "baseName": "reflectedType",
            "type": "Type",
            "format": ""
        },
        {
            "name": "module",
            "baseName": "module",
            "type": "Module",
            "format": ""
        },
        {
            "name": "customAttributes",
            "baseName": "customAttributes",
            "type": "Array<CustomAttributeData>",
            "format": ""
        },
        {
            "name": "isCollectible",
            "baseName": "isCollectible",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "metadataToken",
            "baseName": "metadataToken",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "memberType",
            "baseName": "memberType",
            "type": "MemberTypes",
            "format": ""
        },
        {
            "name": "propertyType",
            "baseName": "propertyType",
            "type": "Type",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "PropertyAttributes",
            "format": ""
        },
        {
            "name": "isSpecialName",
            "baseName": "isSpecialName",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "canRead",
            "baseName": "canRead",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "canWrite",
            "baseName": "canWrite",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "getMethod",
            "baseName": "getMethod",
            "type": "MethodInfo",
            "format": ""
        },
        {
            "name": "setMethod",
            "baseName": "setMethod",
            "type": "MethodInfo",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PropertyInfo.attributeTypeMap;
    }

    public constructor() {
    }
}



