/**
 * GameTrip.API
 * GameTrip API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class RegisterDTO {
    'username': string;
    'email': string;
    'password': string;
    'confirmPassword': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "username",
            "baseName": "username",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": "email"
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string",
            "format": "password"
        },
        {
            "name": "confirmPassword",
            "baseName": "confirmPassword",
            "type": "string",
            "format": "password"
        }    ];

    static getAttributeTypeMap() {
        return RegisterDTO.attributeTypeMap;
    }

    public constructor() {
    }
}

