/**
 * GameTrip.API
 * GameTrip API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Game } from '../models/Game';
import { Location } from '../models/Location';
import { Picture } from '../models/Picture';
import { HttpFile } from '../http/http';

export class RequestLocationUpdate {
    'idRequestLocationUpdate'?: string;
    'locationId'?: string;
    'location'?: Location;
    'name'?: string | null;
    'description'?: string | null;
    'latitude'?: number | null;
    'longitude'?: number | null;
    'idPicture'?: string | null;
    'picture'?: Picture;
    'isAddedPicture'?: boolean | null;
    'idGame'?: string | null;
    'game'?: Game;
    'isAddedGame'?: boolean | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "idRequestLocationUpdate",
            "baseName": "idRequestLocationUpdate",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "locationId",
            "baseName": "locationId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "Location",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "latitude",
            "baseName": "latitude",
            "type": "number",
            "format": "double"
        },
        {
            "name": "longitude",
            "baseName": "longitude",
            "type": "number",
            "format": "double"
        },
        {
            "name": "idPicture",
            "baseName": "idPicture",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "picture",
            "baseName": "picture",
            "type": "Picture",
            "format": ""
        },
        {
            "name": "isAddedPicture",
            "baseName": "isAddedPicture",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "idGame",
            "baseName": "idGame",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "game",
            "baseName": "game",
            "type": "Game",
            "format": ""
        },
        {
            "name": "isAddedGame",
            "baseName": "isAddedGame",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RequestLocationUpdate.attributeTypeMap;
    }

    public constructor() {
    }
}

