/**
 * GameTrip.API
 * GameTrip API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LocationDto } from '../models/LocationDto';
import { HttpFile } from '../http/http';

export class SearchedGameDto {
    'id'?: string | null;
    'name'?: string | null;
    'authorId'?: string;
    'isValidate'?: boolean;
    'locations'?: Array<LocationDto> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "authorId",
            "baseName": "authorId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "isValidate",
            "baseName": "isValidate",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "locations",
            "baseName": "locations",
            "type": "Array<LocationDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SearchedGameDto.attributeTypeMap;
    }

    public constructor() {
    }
}

