/**
 * GameTrip.API
 * GameTrip API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LayoutKind } from '../models/LayoutKind';
import { HttpFile } from '../http/http';

export class StructLayoutAttribute {
    'typeId'?: any | null;
    'value'?: LayoutKind;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "typeId",
            "baseName": "typeId",
            "type": "any",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "LayoutKind",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StructLayoutAttribute.attributeTypeMap;
    }

    public constructor() {
    }
}



