/**
 * GameTrip.API
 * Fifty Cent API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TestModel {
    'test'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "test",
            "baseName": "test",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TestModel.attributeTypeMap;
    }

    public constructor() {
    }
}

