/**
 * GameTrip.API
 * GameTrip API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export type TypeAttributes = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "16" | "24" | "32" | "128" | "256" | "1024" | "2048" | "4096" | "8192" | "16384" | "65536" | "131072" | "196608" | "262144" | "264192" | "1048576" | "12582912" ;
